name: Tests

on: [push, pull_request]

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
         submodules: recursive 

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.X

      - name: Install Node Dependecies 
        run: npm install
      
      - name: Compile Smart Contracts
        run: npx hardhat compile
      
      - name: Hardhat Tests
        run: npx hardhat test
      
      - name: Check formatting
        run: forge fmt --check

      - name: Check formatting
        run: forge snapshot --check


      - name: Run tests
        run: forge test -vvv
        env:
          # Change profile to prod. when deploying to production.
          FOUNDRY_PROFILE: ${{ (github.ref == 'refs/heads/main' || github.base_ref == 'main') && 'prod' }}